### ISSUE TITLE
Local installation issues

### ISSUE THREAD

**Issue by Cmurilochem** [esciencecenter-digital-skills/NEBULA-docs#6]
Hi @JaroCamphuijsen and @raar1. While trying to make a local fresh installation of NEBULA via `npm install` I have the error: 
```console
ERROR  Cannot find module '../content_config/config.json'
```
This is coming from [nuxt.config.ts](https://github.com/esciencecenter-digital-skills/NEBULA/blob/main/nuxt.config.ts):
https://github.com/esciencecenter-digital-skills/NEBULA/blob/5c069ac8c967eb2a987508688bb504d3bda7bcb8/nuxt.config.ts#L3

I did not experience this before and it looks like that the `content_config` argument should be replaced by the name of the content repo like "../research-software-support/config.json"

If I run `npm install` from the `research-software-repo` is get another error:
```console
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/Users/murilo/Library/CloudStorage/OneDrive-NetherlandseScienceCenter/Documents/NLeSC_Projects/RSS_sprint/research-software-support/package.json'
```

It seems that it cannot find a `package.json` within  `research-software-repo`. Am I missing something ? If so, sorry for this.

**Comment by JaroCamphuijsen** [comment]
I'm adding documentation on how to setup a local build in esciencecenter-digital-skills/NEBULA#29

**Comment by Cmurilochem** [comment]
Thanks!
